version: "3"
services:
  mysql:
    container_name: gradlemall_db
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gradlemall
      MYSQL_USER: jiyongd
      MYSQL_PASSWORD: "1234"
      MYSQL_HOST: gradlemall
    volumes:
      - db-data:/var/lib/mysql
      - ./db_init/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306

  gradlemall-admin-api:
    container_name: gradlemall_admin_api
    image: openjdk:11
    volumes:
      - ../gradleAdminApi:/api/gradleAdminApi
      - ../uploadedImages:/api/uploadedImages
    ports:
      - 8080:8080
    depends_on:
      - mysql
    command: /bin/sh -c "cd /api/gradleAdminApi && SPRING_PROFILES_ACTIVE=docker ./gradlew bootRun"

  gradlemall-admin-front:
    container_name: gradlemall_admin_front
    build:
      context: .
      dockerfile: DockerfileFront
    volumes:
      - ../gradleAdminFront:/web/gradleAdminFront
      - ../uploadedImages:/web/uploadedImages
    ports:
      - 3000:3000
    command: /bin/sh -c "cd /web/gradleAdminFront && yarn install && yarn dev"
    healthcheck:
      test: curl -sS http://localhost:8080 || exit 1
      timeout: 10s
      retries: 10
    environment:
      - ENV=${ENV}

volumes:
  db-data:
